import CardanoKeri
#print axioms CardanoKeri.Cage.AuthMode.delegated.sizeOf_spec
#print axioms CardanoKeri.Cage.AuthMode.ofNat_ctorIdx
#print axioms CardanoKeri.Cage.AuthMode.ownerAndHook.sizeOf_spec
#print axioms CardanoKeri.Cage.AuthMode.ownerKeyed.sizeOf_spec
#print axioms CardanoKeri.Cage.Plugin.mk.inj
#print axioms CardanoKeri.Cage.Plugin.mk.injEq
#print axioms CardanoKeri.Cage.Plugin.mk.sizeOf_spec
#print axioms CardanoKeri.Cage.Plugin.registry.eq_1
#print axioms CardanoKeri.Cage.TxAuth.mk.inj
#print axioms CardanoKeri.Cage.TxAuth.mk.injEq
#print axioms CardanoKeri.Cage.TxAuth.mk.sizeOf_spec
#print axioms CardanoKeri.Cage.ValueMode.delegatedRouting.sizeOf_spec
#print axioms CardanoKeri.Cage.ValueMode.ofNat_ctorIdx
#print axioms CardanoKeri.Cage.ValueMode.refundAll.sizeOf_spec
#print axioms CardanoKeri.Cage.applyBatch.eq_1
#print axioms CardanoKeri.Cage.applyBatch.eq_2
#print axioms CardanoKeri.Cage.applyBatch_delegated_eq
#print axioms CardanoKeri.Cage.applyBatch_delegated_eq._simp_1_13
#print axioms CardanoKeri.Cage.authorized.eq_1
#print axioms CardanoKeri.Cage.authorized.eq_2
#print axioms CardanoKeri.Cage.authorized.eq_3
#print axioms CardanoKeri.Cage.bypassed.eq_1
#print axioms CardanoKeri.Cage.bypassed_breaks_inv
#print axioms CardanoKeri.Cage.delegated_is_registry
#print axioms CardanoKeri.Cage.delegated_permissionless
#print axioms CardanoKeri.Cage.delegated_pins_plugin
#print axioms CardanoKeri.Cage.instDecidableEqAuthMode._proof_1
#print axioms CardanoKeri.Cage.instDecidableEqAuthMode._proof_2
#print axioms CardanoKeri.Cage.instDecidableEqTxAuth.decEq._proof_1
#print axioms CardanoKeri.Cage.instDecidableEqTxAuth.decEq._proof_2
#print axioms CardanoKeri.Cage.instDecidableEqTxAuth.decEq._proof_3
#print axioms CardanoKeri.Cage.instDecidableEqValueMode._proof_1
#print axioms CardanoKeri.Cage.instDecidableEqValueMode._proof_2
#print axioms CardanoKeri.Cage.ownerAndHook_needs_owner
#print axioms CardanoKeri.Cage.ownerAndHook_trivial_breaks_inv
#print axioms CardanoKeri.Cage.ownerKeyed_needs_owner
#print axioms CardanoKeri.Cage.owner_bypass_breaks_inv
#print axioms CardanoKeri.Cage.owner_swaps_plugin
#print axioms CardanoKeri.Cage.refundAll_fold_locks_nothing
#print axioms CardanoKeri.Cage.refundAll_never_locks
#print axioms CardanoKeri.Cage.rejectAllowed.eq_1
#print axioms CardanoKeri.Cage.routeValue.eq_1
#print axioms CardanoKeri.Cage.routeValue.eq_2
#print axioms CardanoKeri.Cage.runBody.eq_1
#print axioms CardanoKeri.Cage.stepFn.eq_1
#print axioms CardanoKeri.Cage.stepFn.eq_2
#print axioms CardanoKeri.Cage.wp._proof_1
#print axioms CardanoKeri.Cage.wp._proof_2
#print axioms CardanoKeri.Cage.wp._proof_3
#print axioms CardanoKeri.Checkpoint.Action.actor.eq_1
#print axioms CardanoKeri.Checkpoint.Action.actor.eq_2
#print axioms CardanoKeri.Checkpoint.Action.actor.eq_3
#print axioms CardanoKeri.Checkpoint.Action.actor.eq_4
#print axioms CardanoKeri.Checkpoint.Action.actor.eq_5
#print axioms CardanoKeri.Checkpoint.Action.actor.eq_6
#print axioms CardanoKeri.Checkpoint.Action.actor.eq_7
#print axioms CardanoKeri.Checkpoint.Action.actor.eq_8
#print axioms CardanoKeri.Checkpoint.Action.close.inj
#print axioms CardanoKeri.Checkpoint.Action.close.injEq
#print axioms CardanoKeri.Checkpoint.Action.close.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Action.convict.inj
#print axioms CardanoKeri.Checkpoint.Action.convict.injEq
#print axioms CardanoKeri.Checkpoint.Action.convict.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Action.freeze.inj
#print axioms CardanoKeri.Checkpoint.Action.freeze.injEq
#print axioms CardanoKeri.Checkpoint.Action.freeze.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Action.poison.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Action.register.inj
#print axioms CardanoKeri.Checkpoint.Action.register.injEq
#print axioms CardanoKeri.Checkpoint.Action.register.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Action.reopen.inj
#print axioms CardanoKeri.Checkpoint.Action.reopen.injEq
#print axioms CardanoKeri.Checkpoint.Action.reopen.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Action.rotate.inj
#print axioms CardanoKeri.Checkpoint.Action.rotate.injEq
#print axioms CardanoKeri.Checkpoint.Action.rotate.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Action.topUp.inj
#print axioms CardanoKeri.Checkpoint.Action.topUp.injEq
#print axioms CardanoKeri.Checkpoint.Action.topUp.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Action.touchesLeaf.eq_1
#print axioms CardanoKeri.Checkpoint.Action.touchesLeaf.eq_2
#print axioms CardanoKeri.Checkpoint.Action.touchesLeaf.eq_3
#print axioms CardanoKeri.Checkpoint.Action.touchesLeaf.eq_4
#print axioms CardanoKeri.Checkpoint.Action.touchesLeaf.eq_5
#print axioms CardanoKeri.Checkpoint.Actor.anyone.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Actor.currentQuorum.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Actor.nextKeys.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Actor.ofNat_ctorIdx
#print axioms CardanoKeri.Checkpoint.Actor.proof.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.BondOp.deposit.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.BondOp.intent.eq_1
#print axioms CardanoKeri.Checkpoint.BondOp.intent.eq_2
#print axioms CardanoKeri.Checkpoint.BondOp.keep.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.BondOp.ofNat_ctorIdx
#print axioms CardanoKeri.Checkpoint.Env.intentOk.eq_1
#print axioms CardanoKeri.Checkpoint.Env.intentOk.eq_2
#print axioms CardanoKeri.Checkpoint.Env.mk.inj
#print axioms CardanoKeri.Checkpoint.Env.mk.injEq
#print axioms CardanoKeri.Checkpoint.Env.mk.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Flow.mk.inj
#print axioms CardanoKeri.Checkpoint.Flow.mk.injEq
#print axioms CardanoKeri.Checkpoint.Flow.mk.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Intent.close.inj
#print axioms CardanoKeri.Checkpoint.Intent.close.injEq
#print axioms CardanoKeri.Checkpoint.Intent.close.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Intent.deposit.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Intent.keep.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.KeyState.mk.inj
#print axioms CardanoKeri.Checkpoint.KeyState.mk.injEq
#print axioms CardanoKeri.Checkpoint.KeyState.mk.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Leaf.absent.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Leaf.active.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Leaf.convicted.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Leaf.parked.inj
#print axioms CardanoKeri.Checkpoint.Leaf.parked.injEq
#print axioms CardanoKeri.Checkpoint.Leaf.parked.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Live.bHeld.eq_1
#print axioms CardanoKeri.Checkpoint.Live.mk.inj
#print axioms CardanoKeri.Checkpoint.Live.mk.injEq
#print axioms CardanoKeri.Checkpoint.Live.mk.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Live.rotated.eq_1
#print axioms CardanoKeri.Checkpoint.Params.hB
#print axioms CardanoKeri.Checkpoint.Params.hD
#print axioms CardanoKeri.Checkpoint.Params.mk.inj
#print axioms CardanoKeri.Checkpoint.Params.mk.injEq
#print axioms CardanoKeri.Checkpoint.Params.mk.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Params.premium.eq_1
#print axioms CardanoKeri.Checkpoint.Payment.mk.inj
#print axioms CardanoKeri.Checkpoint.Payment.mk.injEq
#print axioms CardanoKeri.Checkpoint.Payment.mk.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Payment?.b.eq_1
#print axioms CardanoKeri.Checkpoint.Payment?.b.eq_2
#print axioms CardanoKeri.Checkpoint.Payment?.dreg.eq_1
#print axioms CardanoKeri.Checkpoint.Payment?.dreg.eq_2
#print axioms CardanoKeri.Checkpoint.Payment?.pool.eq_1
#print axioms CardanoKeri.Checkpoint.Payment?.pool.eq_2
#print axioms CardanoKeri.Checkpoint.State.absent.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.State.bHeld.eq_1
#print axioms CardanoKeri.Checkpoint.State.bHeld.eq_2
#print axioms CardanoKeri.Checkpoint.State.convicted.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.State.dregHeld.eq_1
#print axioms CardanoKeri.Checkpoint.State.dregHeld.eq_2
#print axioms CardanoKeri.Checkpoint.State.leaf.eq_1
#print axioms CardanoKeri.Checkpoint.State.leaf.eq_2
#print axioms CardanoKeri.Checkpoint.State.leaf.eq_3
#print axioms CardanoKeri.Checkpoint.State.leaf.eq_4
#print axioms CardanoKeri.Checkpoint.State.parked.inj
#print axioms CardanoKeri.Checkpoint.State.parked.injEq
#print axioms CardanoKeri.Checkpoint.State.parked.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.State.poolHeld.eq_1
#print axioms CardanoKeri.Checkpoint.State.poolHeld.eq_2
#print axioms CardanoKeri.Checkpoint.State.present.inj
#print axioms CardanoKeri.Checkpoint.State.present.injEq
#print axioms CardanoKeri.Checkpoint.State.present.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.State.sn?.eq_1
#print axioms CardanoKeri.Checkpoint.State.sn?.eq_2
#print axioms CardanoKeri.Checkpoint.State.sn?.eq_3
#print axioms CardanoKeri.Checkpoint.State.sn?.eq_4
#print axioms CardanoKeri.Checkpoint.Step.closePaid_iff
#print axioms CardanoKeri.Checkpoint.Step.closeUnpaid_iff
#print axioms CardanoKeri.Checkpoint.Step.convictParked_iff
#print axioms CardanoKeri.Checkpoint.Step.convict_iff
#print axioms CardanoKeri.Checkpoint.Step.freeze_iff
#print axioms CardanoKeri.Checkpoint.Step.poison_iff
#print axioms CardanoKeri.Checkpoint.Step.register_iff
#print axioms CardanoKeri.Checkpoint.Step.reopen_iff
#print axioms CardanoKeri.Checkpoint.Step.rotateDepositPaid_iff
#print axioms CardanoKeri.Checkpoint.Step.rotateDepositUnpaid_iff
#print axioms CardanoKeri.Checkpoint.Step.rotateKeepPaid_iff
#print axioms CardanoKeri.Checkpoint.Step.rotateKeepUnpaid_iff
#print axioms CardanoKeri.Checkpoint.Step.topUp_iff
#print axioms CardanoKeri.Checkpoint.Sys.mk.inj
#print axioms CardanoKeri.Checkpoint.Sys.mk.injEq
#print axioms CardanoKeri.Checkpoint.Sys.mk.sizeOf_spec
#print axioms CardanoKeri.Checkpoint.Sys.set.eq_1
#print axioms CardanoKeri.Checkpoint.SysReach.brecOn
#print axioms CardanoKeri.Checkpoint.T10_bonds_are_observable
#print axioms CardanoKeri.Checkpoint.T10_bonds_are_observable._proof_1_4
#print axioms CardanoKeri.Checkpoint.T10_bonds_are_observable._proof_1_8
#print axioms CardanoKeri.Checkpoint.T10_current_quorum_never_restores
#print axioms CardanoKeri.Checkpoint.T10_inert_without_next_keys
#print axioms CardanoKeri.Checkpoint.T10_only_deposit_restores
#print axioms CardanoKeri.Checkpoint.T10_parked_holds_nothing
#print axioms CardanoKeri.Checkpoint.T10_reopen_is_juvenile
#print axioms CardanoKeri.Checkpoint.T10_reopen_is_juvenile._proof_1_4
#print axioms CardanoKeri.Checkpoint.T12_convict_exact
#print axioms CardanoKeri.Checkpoint.T12_convict_parked_exact
#print axioms CardanoKeri.Checkpoint.T12_convicted_terminal
#print axioms CardanoKeri.Checkpoint.T14_pool_decreases_only_by_premium
#print axioms CardanoKeri.Checkpoint.T14_pool_decreases_only_by_premium._proof_1_13
#print axioms CardanoKeri.Checkpoint.T14_pool_increases_only_by_topup
#print axioms CardanoKeri.Checkpoint.T14_pool_increases_only_by_topup._proof_1_1
#print axioms CardanoKeri.Checkpoint.T14_pool_increases_only_by_topup._proof_1_2
#print axioms CardanoKeri.Checkpoint.T14_pool_increases_only_by_topup._proof_1_3
#print axioms CardanoKeri.Checkpoint.T15_b_leaves_only_by_freeze
#print axioms CardanoKeri.Checkpoint.T15_b_returns_only_by_deposit
#print axioms CardanoKeri.Checkpoint.T15_freeze_makes_inert
#print axioms CardanoKeri.Checkpoint.T16_close_destination
#print axioms CardanoKeri.Checkpoint.T16_close_destination._proof_1_6
#print axioms CardanoKeri.Checkpoint.T16_close_needs_rotation
#print axioms CardanoKeri.Checkpoint.T16_copied_reap_refused
#print axioms CardanoKeri.Checkpoint.T16_parked_hash_is_the_closed_checkpoints
#print axioms CardanoKeri.Checkpoint.T16_parked_hash_is_the_closed_checkpoints._proof_1_7
#print axioms CardanoKeri.Checkpoint.T16_payments_are_named
#print axioms CardanoKeri.Checkpoint.T1_close_rotation_cannot_revive
#print axioms CardanoKeri.Checkpoint.T1_reopen_strict
#print axioms CardanoKeri.Checkpoint.T1_rotate_strict
#print axioms CardanoKeri.Checkpoint.T1_sn_monotone
#print axioms CardanoKeri.Checkpoint.T1_sn_monotone_all
#print axioms CardanoKeri.Checkpoint.T1_sn_monotone_all._proof_1_6
#print axioms CardanoKeri.Checkpoint.T1_sn_monotone_all._proof_1_7
#print axioms CardanoKeri.Checkpoint.T1_trace_sn_monotone
#print axioms CardanoKeri.Checkpoint.T2_close_and_reopen_open_epochs
#print axioms CardanoKeri.Checkpoint.T2_epoch_only_by_rotation
#print axioms CardanoKeri.Checkpoint.T3_epoch_local
#print axioms CardanoKeri.Checkpoint.T3_only_poison_sets
#print axioms CardanoKeri.Checkpoint.T3_only_rotation_clears
#print axioms CardanoKeri.Checkpoint.T3_rotation_clears
#print axioms CardanoKeri.Checkpoint.T4_current_key_thief_cannot_park
#print axioms CardanoKeri.Checkpoint.T4_current_key_thief_cannot_revive
#print axioms CardanoKeri.Checkpoint.T4_current_quorum_only_poisons
#print axioms CardanoKeri.Checkpoint.T4_poisoned_blocks_quorum_and_freeze
#print axioms CardanoKeri.Checkpoint.T4_poisoned_nonrotation_inert
#print axioms CardanoKeri.Checkpoint.T5_close_enabled
#print axioms CardanoKeri.Checkpoint.T5_convict_enabled
#print axioms CardanoKeri.Checkpoint.T5_convict_parked_enabled
#print axioms CardanoKeri.Checkpoint.T5_deposit_on_full_is_keep
#print axioms CardanoKeri.Checkpoint.T5_deposit_on_full_is_keep._proof_1_4
#print axioms CardanoKeri.Checkpoint.T5_every_bond_option
#print axioms CardanoKeri.Checkpoint.T5_freeze_enabled
#print axioms CardanoKeri.Checkpoint.T5_keep_is_rotated
#print axioms CardanoKeri.Checkpoint.T5_keep_needs_no_intent
#print axioms CardanoKeri.Checkpoint.T5_poison_enabled
#print axioms CardanoKeri.Checkpoint.T5_reopen_enabled
#print axioms CardanoKeri.Checkpoint.T6_component_conservation
#print axioms CardanoKeri.Checkpoint.T6_dreg_enters_only_at_birth
#print axioms CardanoKeri.Checkpoint.T6_dreg_never_a_fee
#print axioms CardanoKeri.Checkpoint.T6_dreg_never_moves_between_present_states
#print axioms CardanoKeri.Checkpoint.T6_frozen_flips_only_by_rotation_or_freeze
#print axioms CardanoKeri.Checkpoint.T6_intent_requires_new_keys
#print axioms CardanoKeri.Checkpoint.T6_refund_change_requires_new_keys
#print axioms CardanoKeri.Checkpoint.T6_relayer_cannot_park_age_or_close
#print axioms CardanoKeri.Checkpoint.T7_step_iff_stepFn
#print axioms CardanoKeri.Checkpoint.T7_trace_iff_replay
#print axioms CardanoKeri.Checkpoint.T8_absent_only_registers
#print axioms CardanoKeri.Checkpoint.T8_edges_leave_the_leaf
#print axioms CardanoKeri.Checkpoint.T8_leaf_agrees_with_state
#print axioms CardanoKeri.Checkpoint.T8_leaf_never_absent_again
#print axioms CardanoKeri.Checkpoint.T8_leaf_states
#print axioms CardanoKeri.Checkpoint.T8_mint_once
#print axioms CardanoKeri.Checkpoint.T8_only_convicted_is_terminal
#print axioms CardanoKeri.Checkpoint.T8_parked_only_revives_or_convicts
#print axioms CardanoKeri.Checkpoint.T8_parked_returns_only_by_revival
#print axioms CardanoKeri.Checkpoint.T8_present_implies_registered
#print axioms CardanoKeri.Checkpoint.T8_reopen_actor_is_proof
#print axioms CardanoKeri.Checkpoint.T8_sysstep_partition
#print axioms CardanoKeri.Checkpoint.T8_utxo_iff_active
#print axioms CardanoKeri.Checkpoint.T9_juvenility_is_consumer_only
#print axioms CardanoKeri.Checkpoint.Trace.brecOn
#print axioms CardanoKeri.Checkpoint.consumableState.eq_1
#print axioms CardanoKeri.Checkpoint.consumableState.eq_2
#print axioms CardanoKeri.Checkpoint.consumableStateB.eq_1
#print axioms CardanoKeri.Checkpoint.consumableStateB.eq_2
#print axioms CardanoKeri.Checkpoint.consumableStateB_iff
#print axioms CardanoKeri.Checkpoint.consumableStateB_iff._simp_1_6
#print axioms CardanoKeri.Checkpoint.instDecidableEqActor._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqActor._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqBondOp._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqBondOp._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqFlow.decEq._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqFlow.decEq._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqFlow.decEq._proof_3
#print axioms CardanoKeri.Checkpoint.instDecidableEqFlow.decEq._proof_4
#print axioms CardanoKeri.Checkpoint.instDecidableEqFlow.decEq._proof_5
#print axioms CardanoKeri.Checkpoint.instDecidableEqFlow.decEq._proof_6
#print axioms CardanoKeri.Checkpoint.instDecidableEqFlow.decEq._proof_7
#print axioms CardanoKeri.Checkpoint.instDecidableEqIntent.decEq._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqIntent.decEq._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqIntent.decEq._proof_3
#print axioms CardanoKeri.Checkpoint.instDecidableEqIntent.decEq._proof_4
#print axioms CardanoKeri.Checkpoint.instDecidableEqIntent.decEq._proof_5
#print axioms CardanoKeri.Checkpoint.instDecidableEqIntent.decEq._proof_6
#print axioms CardanoKeri.Checkpoint.instDecidableEqIntent.decEq._proof_7
#print axioms CardanoKeri.Checkpoint.instDecidableEqIntent.decEq._proof_8
#print axioms CardanoKeri.Checkpoint.instDecidableEqKeyState.decEq._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqKeyState.decEq._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqKeyState.decEq._proof_3
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_10
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_11
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_12
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_13
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_14
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_3
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_4
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_5
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_6
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_7
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_8
#print axioms CardanoKeri.Checkpoint.instDecidableEqLeaf.decEq._proof_9
#print axioms CardanoKeri.Checkpoint.instDecidableEqLive.decEq._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqLive.decEq._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqLive.decEq._proof_3
#print axioms CardanoKeri.Checkpoint.instDecidableEqLive.decEq._proof_4
#print axioms CardanoKeri.Checkpoint.instDecidableEqLive.decEq._proof_5
#print axioms CardanoKeri.Checkpoint.instDecidableEqLive.decEq._proof_6
#print axioms CardanoKeri.Checkpoint.instDecidableEqLive.decEq._proof_7
#print axioms CardanoKeri.Checkpoint.instDecidableEqLive.decEq._proof_8
#print axioms CardanoKeri.Checkpoint.instDecidableEqPayment.decEq._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqPayment.decEq._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqPayment.decEq._proof_3
#print axioms CardanoKeri.Checkpoint.instDecidableEqPayment.decEq._proof_4
#print axioms CardanoKeri.Checkpoint.instDecidableEqPayment.decEq._proof_5
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_1
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_10
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_11
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_12
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_13
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_14
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_15
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_16
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_2
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_3
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_4
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_5
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_6
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_7
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_8
#print axioms CardanoKeri.Checkpoint.instDecidableEqState.decEq._proof_9
#print axioms CardanoKeri.Checkpoint.poisonAfter.eq_1
#print axioms CardanoKeri.Checkpoint.poisonAfter.eq_2
#print axioms CardanoKeri.Checkpoint.poisonAfter.eq_3
#print axioms CardanoKeri.Checkpoint.poisonAfter.eq_4
#print axioms CardanoKeri.Checkpoint.poisonAfter.eq_5
#print axioms CardanoKeri.Checkpoint.poisonAfter.eq_6
#print axioms CardanoKeri.Checkpoint.poisonSinceLastRotation.eq_1
#print axioms CardanoKeri.Checkpoint.replay.eq_1
#print axioms CardanoKeri.Checkpoint.replay.eq_2
#print axioms CardanoKeri.Checkpoint.stepFn.eq_1
#print axioms CardanoKeri.Checkpoint.stepFn.eq_10
#print axioms CardanoKeri.Checkpoint.stepFn.eq_2
#print axioms CardanoKeri.Checkpoint.stepFn.eq_3
#print axioms CardanoKeri.Checkpoint.stepFn.eq_4
#print axioms CardanoKeri.Checkpoint.stepFn.eq_5
#print axioms CardanoKeri.Checkpoint.stepFn.eq_6
#print axioms CardanoKeri.Checkpoint.stepFn.eq_7
#print axioms CardanoKeri.Checkpoint.stepFn.eq_8
#print axioms CardanoKeri.Checkpoint.stepFn.eq_9
#print axioms CardanoKeri.Checkpoint.trace_from_convicted
#print axioms CardanoKeri.Checkpoint.trace_poison_fold
#print axioms CardanoKeri.Checkpoint.trace_sn_monotone_all
#print axioms CardanoKeri.Registry.Acc.mk.inj
#print axioms CardanoKeri.Registry.Acc.mk.injEq
#print axioms CardanoKeri.Registry.Acc.mk.sizeOf_spec
#print axioms CardanoKeri.Registry.AccInv.activeCkpt
#print axioms CardanoKeri.Registry.AccInv.ckptActive
#print axioms CardanoKeri.Registry.AccInv.ckptNodup
#print axioms CardanoKeri.Registry.AccInv.goActive
#print axioms CardanoKeri.Registry.AccInv.goFar
#print axioms CardanoKeri.Registry.AccInv.goNoCkpt
#print axioms CardanoKeri.Registry.AccInv.goUnique
#print axioms CardanoKeri.Registry.AccInv.leafNodup
#print axioms CardanoKeri.Registry.AccInv.reqBelowNext
#print axioms CardanoKeri.Registry.AccInv.reqNodup
#print axioms CardanoKeri.Registry.Action.contribute.inj
#print axioms CardanoKeri.Registry.Action.contribute.injEq
#print axioms CardanoKeri.Registry.Action.contribute.sizeOf_spec
#print axioms CardanoKeri.Registry.Action.convictCkpt.inj
#print axioms CardanoKeri.Registry.Action.convictCkpt.injEq
#print axioms CardanoKeri.Registry.Action.convictCkpt.sizeOf_spec
#print axioms CardanoKeri.Registry.Action.fold.inj
#print axioms CardanoKeri.Registry.Action.fold.injEq
#print axioms CardanoKeri.Registry.Action.fold.sizeOf_spec
#print axioms CardanoKeri.Registry.Action.pause.inj
#print axioms CardanoKeri.Registry.Action.pause.injEq
#print axioms CardanoKeri.Registry.Action.pause.sizeOf_spec
#print axioms CardanoKeri.Registry.Action.reap.inj
#print axioms CardanoKeri.Registry.Action.reap.injEq
#print axioms CardanoKeri.Registry.Action.reap.sizeOf_spec
#print axioms CardanoKeri.Registry.Action.resume.inj
#print axioms CardanoKeri.Registry.Action.resume.injEq
#print axioms CardanoKeri.Registry.Action.resume.sizeOf_spec
#print axioms CardanoKeri.Registry.Action.retract.inj
#print axioms CardanoKeri.Registry.Action.retract.injEq
#print axioms CardanoKeri.Registry.Action.retract.sizeOf_spec
#print axioms CardanoKeri.Registry.Actor.anyone.sizeOf_spec
#print axioms CardanoKeri.Registry.Actor.nextKeys.sizeOf_spec
#print axioms CardanoKeri.Registry.Actor.ofNat_ctorIdx
#print axioms CardanoKeri.Registry.Actor.owner.sizeOf_spec
#print axioms CardanoKeri.Registry.Actor.proof.sizeOf_spec
#print axioms CardanoKeri.Registry.CkState.live.sizeOf_spec
#print axioms CardanoKeri.Registry.CkState.parked.inj
#print axioms CardanoKeri.Registry.CkState.parked.injEq
#print axioms CardanoKeri.Registry.CkState.parked.sizeOf_spec
#print axioms CardanoKeri.Registry.CkState.tomb.sizeOf_spec
#print axioms CardanoKeri.Registry.Ckpt.mk.inj
#print axioms CardanoKeri.Registry.Ckpt.mk.injEq
#print axioms CardanoKeri.Registry.Ckpt.mk.sizeOf_spec
#print axioms CardanoKeri.Registry.Env.mk.inj
#print axioms CardanoKeri.Registry.Env.mk.injEq
#print axioms CardanoKeri.Registry.Env.mk.sizeOf_spec
#print axioms CardanoKeri.Registry.Flow.mk.inj
#print axioms CardanoKeri.Registry.Flow.mk.injEq
#print axioms CardanoKeri.Registry.Flow.mk.sizeOf_spec
#print axioms CardanoKeri.Registry.FoldAction.ofNat_ctorIdx
#print axioms CardanoKeri.Registry.FoldAction.process.sizeOf_spec
#print axioms CardanoKeri.Registry.FoldAction.reject.sizeOf_spec
#print axioms CardanoKeri.Registry.Inv.activeCkpt
#print axioms CardanoKeri.Registry.Inv.ckptActive
#print axioms CardanoKeri.Registry.Inv.ckptNodup
#print axioms CardanoKeri.Registry.Inv.goActive
#print axioms CardanoKeri.Registry.Inv.goFar
#print axioms CardanoKeri.Registry.Inv.goNoCkpt
#print axioms CardanoKeri.Registry.Inv.goUnique
#print axioms CardanoKeri.Registry.Inv.leafNodup
#print axioms CardanoKeri.Registry.Inv.reqBelowNext
#print axioms CardanoKeri.Registry.Inv.reqNodup
#print axioms CardanoKeri.Registry.Op.convict.sizeOf_spec
#print axioms CardanoKeri.Registry.Op.goConvicted.sizeOf_spec
#print axioms CardanoKeri.Registry.Op.goDormant.inj
#print axioms CardanoKeri.Registry.Op.goDormant.injEq
#print axioms CardanoKeri.Registry.Op.goDormant.sizeOf_spec
#print axioms CardanoKeri.Registry.Op.register.sizeOf_spec
#print axioms CardanoKeri.Registry.Op.revive.sizeOf_spec
#print axioms CardanoKeri.Registry.Op.userPostable.eq_1
#print axioms CardanoKeri.Registry.Op.userPostable.eq_2
#print axioms CardanoKeri.Registry.Op.userPostable.eq_3
#print axioms CardanoKeri.Registry.Op.userPostable.eq_4
#print axioms CardanoKeri.Registry.Params.hD
#print axioms CardanoKeri.Registry.Params.hFund
#print axioms CardanoKeri.Registry.Params.hProcess
#print axioms CardanoKeri.Registry.Params.hRetract
#print axioms CardanoKeri.Registry.Params.mk.inj
#print axioms CardanoKeri.Registry.Params.mk.injEq
#print axioms CardanoKeri.Registry.Params.mk.sizeOf_spec
#print axioms CardanoKeri.Registry.R10_honest_phase1_reject_exclusive
#print axioms CardanoKeri.Registry.R10_honest_phase1_reject_exclusive._proof_1_1
#print axioms CardanoKeri.Registry.R10_phase1_phase2_exclusive
#print axioms CardanoKeri.Registry.R10_phase1_phase2_exclusive._proof_1_1
#print axioms CardanoKeri.Registry.R10_phase2_reject_exclusive
#print axioms CardanoKeri.Registry.R10_phase2_reject_exclusive._proof_1_1
#print axioms CardanoKeri.Registry.R11_ckpt_edges_move_no_value
#print axioms CardanoKeri.Registry.R11_contribute_value
#print axioms CardanoKeri.Registry.R11_go_refunds_reaper
#print axioms CardanoKeri.Registry.R11_reap_flow
#print axioms CardanoKeri.Registry.R11_reap_is_samaritan
#print axioms CardanoKeri.Registry.R11_retract_value
#print axioms CardanoKeri.Registry.R11_samaritan_never_loses
#print axioms CardanoKeri.Registry.R12_leaf_changes_only_by_fold
#print axioms CardanoKeri.Registry.R12_leaf_enters_only_by_fold
#print axioms CardanoKeri.Registry.R13_live_never_reaped
#print axioms CardanoKeri.Registry.R13_owner_reaps_early
#print axioms CardanoKeri.Registry.R13_parked_after_grace
#print axioms CardanoKeri.Registry.R13_parked_needs_grace
#print axioms CardanoKeri.Registry.R13_parked_needs_grace._proof_1_2
#print axioms CardanoKeri.Registry.R13_tomb_reaped
#print axioms CardanoKeri.Registry.R14_convictCkpt_needs_proof
#print axioms CardanoKeri.Registry.R14_convict_at_position
#print axioms CardanoKeri.Registry.R14_convict_dormant_needs_proof
#print axioms CardanoKeri.Registry.R14_convict_in_batch_needs_proof
#print axioms CardanoKeri.Registry.R1_active_ckpt_or_go
#print axioms CardanoKeri.Registry.R1_ckpt_implies_active
#print axioms CardanoKeri.Registry.R1_not_active_no_ckpt
#print axioms CardanoKeri.Registry.R1_registered_refused
#print axioms CardanoKeri.Registry.R2_one_ckpt_per_aid
#print axioms CardanoKeri.Registry.R2_one_go_per_aid
#print axioms CardanoKeri.Registry.R2_one_leaf_per_aid
#print axioms CardanoKeri.Registry.R3_convicted_never_registered
#print axioms CardanoKeri.Registry.R3_convicted_permanent
#print axioms CardanoKeri.Registry.R4_leaf_permanent
#print axioms CardanoKeri.Registry.R5_plugin_pinned
#print axioms CardanoKeri.Registry.R6_fold_advances
#print axioms CardanoKeri.Registry.R6_gen_step
#print axioms CardanoKeri.Registry.R6_registry_untouched
#print axioms CardanoKeri.Registry.R7_one_fold_per_generation
#print axioms CardanoKeri.Registry.R7_one_fold_per_generation._proof_1_10
#print axioms CardanoKeri.Registry.R7_stale_fold_refused
#print axioms CardanoKeri.Registry.R8_empty_fold_refused
#print axioms CardanoKeri.Registry.R8_plugin_swap_refused
#print axioms CardanoKeri.Registry.R9_go_never_rejected
#print axioms CardanoKeri.Registry.R9_go_never_retracted
#print axioms CardanoKeri.Registry.R9_reject_enabled
#print axioms CardanoKeri.Registry.R9_reject_needs_rejectable
#print axioms CardanoKeri.Registry.R9_retract_enabled
#print axioms CardanoKeri.Registry.R9_retract_needs_phase2
#print axioms CardanoKeri.Registry.Reach.brecOn
#print axioms CardanoKeri.Registry.ReachFar.brecOn
#print axioms CardanoKeri.Registry.Request.mk.inj
#print axioms CardanoKeri.Registry.Request.mk.injEq
#print axioms CardanoKeri.Registry.Request.mk.sizeOf_spec
#print axioms CardanoKeri.Registry.Status.active.inj
#print axioms CardanoKeri.Registry.Status.active.injEq
#print axioms CardanoKeri.Registry.Status.active.sizeOf_spec
#print axioms CardanoKeri.Registry.Status.convicted.sizeOf_spec
#print axioms CardanoKeri.Registry.Status.dormant.inj
#print axioms CardanoKeri.Registry.Status.dormant.injEq
#print axioms CardanoKeri.Registry.Status.dormant.sizeOf_spec
#print axioms CardanoKeri.Registry.Sys.init.eq_1
#print axioms CardanoKeri.Registry.Sys.mk.inj
#print axioms CardanoKeri.Registry.Sys.mk.injEq
#print axioms CardanoKeri.Registry.Sys.mk.sizeOf_spec
#print axioms CardanoKeri.Registry.accInv_of_inv
#print axioms CardanoKeri.Registry.accInv_remove_postable
#print axioms CardanoKeri.Registry.applyBatch.eq_1
#print axioms CardanoKeri.Registry.applyBatch.eq_2
#print axioms CardanoKeri.Registry.applyBatch_append
#print axioms CardanoKeri.Registry.applyBatch_inv
#print axioms CardanoKeri.Registry.applyBatch_leaf_mono
#print axioms CardanoKeri.Registry.applyBatch_register_registered
#print axioms CardanoKeri.Registry.applyBatch_reject_go
#print axioms CardanoKeri.Registry.applyBatch_unknown
#print axioms CardanoKeri.Registry.eq_of_mem_of_fst_eq
#print axioms CardanoKeri.Registry.fst_ne_of_mem_remove
#print axioms CardanoKeri.Registry.goIn_cons_go
#print axioms CardanoKeri.Registry.goIn_cons_postable
#print axioms CardanoKeri.Registry.goIn_remove_other
#print axioms CardanoKeri.Registry.goIn_remove_postable
#print axioms CardanoKeri.Registry.goInv_after_go
#print axioms CardanoKeri.Registry.goOp.eq_1
#print axioms CardanoKeri.Registry.goOp_not_postable
#print axioms CardanoKeri.Registry.goPending_iff
#print axioms CardanoKeri.Registry.go_not_phase2
#print axioms CardanoKeri.Registry.go_not_phase2._proof_1_1
#print axioms CardanoKeri.Registry.instDecidableEqAcc.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqAcc.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqAcc.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqAcc.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqAcc.decEq._proof_5
#print axioms CardanoKeri.Registry.instDecidableEqAcc.decEq._proof_6
#print axioms CardanoKeri.Registry.instDecidableEqAcc.decEq._proof_7
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_10
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_11
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_12
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_13
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_14
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_15
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_16
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_17
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_18
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_19
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_20
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_21
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_22
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_23
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_24
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_25
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_26
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_27
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_28
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_29
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_30
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_31
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_32
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_33
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_34
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_35
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_36
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_37
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_38
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_39
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_40
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_41
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_42
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_43
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_44
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_45
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_46
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_47
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_48
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_49
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_5
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_50
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_51
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_52
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_53
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_54
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_55
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_56
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_57
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_58
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_59
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_6
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_60
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_61
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_62
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_63
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_7
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_8
#print axioms CardanoKeri.Registry.instDecidableEqAction.decEq._proof_9
#print axioms CardanoKeri.Registry.instDecidableEqActor._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqActor._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqCkState.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqCkState.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqCkState.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqCkState.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqCkState.decEq._proof_5
#print axioms CardanoKeri.Registry.instDecidableEqCkState.decEq._proof_6
#print axioms CardanoKeri.Registry.instDecidableEqCkState.decEq._proof_7
#print axioms CardanoKeri.Registry.instDecidableEqCkState.decEq._proof_8
#print axioms CardanoKeri.Registry.instDecidableEqCkpt.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqCkpt.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqCkpt.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqCkpt.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqFlow.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqFlow.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqFlow.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqFlow.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqFlow.decEq._proof_5
#print axioms CardanoKeri.Registry.instDecidableEqFlow.decEq._proof_6
#print axioms CardanoKeri.Registry.instDecidableEqFlow.decEq._proof_7
#print axioms CardanoKeri.Registry.instDecidableEqFoldAction._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqFoldAction._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_10
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_11
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_12
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_13
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_14
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_15
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_16
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_17
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_18
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_19
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_20
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_21
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_22
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_5
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_6
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_7
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_8
#print axioms CardanoKeri.Registry.instDecidableEqOp.decEq._proof_9
#print axioms CardanoKeri.Registry.instDecidableEqRequest.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqRequest.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqRequest.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqRequest.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqRequest.decEq._proof_5
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_10
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_5
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_6
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_7
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_8
#print axioms CardanoKeri.Registry.instDecidableEqStatus.decEq._proof_9
#print axioms CardanoKeri.Registry.instDecidableEqSys.decEq._proof_1
#print axioms CardanoKeri.Registry.instDecidableEqSys.decEq._proof_2
#print axioms CardanoKeri.Registry.instDecidableEqSys.decEq._proof_3
#print axioms CardanoKeri.Registry.instDecidableEqSys.decEq._proof_4
#print axioms CardanoKeri.Registry.instDecidableEqSys.decEq._proof_5
#print axioms CardanoKeri.Registry.instDecidableEqSys.decEq._proof_6
#print axioms CardanoKeri.Registry.instDecidableEqSys.decEq._proof_7
#print axioms CardanoKeri.Registry.instDecidableEqSys.decEq._proof_8
#print axioms CardanoKeri.Registry.instDecidableReapable._proof_1
#print axioms CardanoKeri.Registry.instDecidableReapable._proof_2
#print axioms CardanoKeri.Registry.instDecidableReapable._proof_3
#print axioms CardanoKeri.Registry.instDecidableReapable._proof_4
#print axioms CardanoKeri.Registry.inv_init
#print axioms CardanoKeri.Registry.inv_of_accInv
#print axioms CardanoKeri.Registry.inv_replace_ckpt
#print axioms CardanoKeri.Registry.inv_step
#print axioms CardanoKeri.Registry.inv_step._proof_1_9
#print axioms CardanoKeri.Registry.key_not_mem_map_fst_remove_self
#print axioms CardanoKeri.Registry.key_not_mem_of_lookup_none
#print axioms CardanoKeri.Registry.lookup.eq_1
#print axioms CardanoKeri.Registry.lookup.eq_2
#print axioms CardanoKeri.Registry.lookup_cons_ne
#print axioms CardanoKeri.Registry.lookup_cons_self
#print axioms CardanoKeri.Registry.lookup_none_of_not_mem
#print axioms CardanoKeri.Registry.lookup_remove_ne
#print axioms CardanoKeri.Registry.lookup_remove_self
#print axioms CardanoKeri.Registry.lookup_setLeaf_ne
#print axioms CardanoKeri.Registry.lookup_setLeaf_self
#print axioms CardanoKeri.Registry.lookup_some_mem
#print axioms CardanoKeri.Registry.lookup_some_of_mem
#print axioms CardanoKeri.Registry.mem_remove
#print axioms CardanoKeri.Registry.mem_remove_of_mem
#print axioms CardanoKeri.Registry.no_ckpt_of_no_leaf
#print axioms CardanoKeri.Registry.no_ckpt_of_not_active
#print axioms CardanoKeri.Registry.nodup_map_remove
#print axioms CardanoKeri.Registry.not_mem_of_lookup_none
#print axioms CardanoKeri.Registry.processBody.eq_1
#print axioms CardanoKeri.Registry.processBody_convict_iff
#print axioms CardanoKeri.Registry.processBody_goConvicted_iff
#print axioms CardanoKeri.Registry.processBody_goDormant_iff
#print axioms CardanoKeri.Registry.processBody_register_iff
#print axioms CardanoKeri.Registry.processBody_revive_iff
#print axioms CardanoKeri.Registry.processOne.eq_1
#print axioms CardanoKeri.Registry.processOne_inv
#print axioms CardanoKeri.Registry.processOne_leaf_mono
#print axioms CardanoKeri.Registry.processOne_register_registered
#print axioms CardanoKeri.Registry.processOne_requests
#print axioms CardanoKeri.Registry.reach_inv
#print axioms CardanoKeri.Registry.reapable.eq_1
#print axioms CardanoKeri.Registry.rejectOne.eq_1
#print axioms CardanoKeri.Registry.rejectOne_go
#print axioms CardanoKeri.Registry.rejectOne_inv
#print axioms CardanoKeri.Registry.rejectOne_leaves
#print axioms CardanoKeri.Registry.remove.eq_1
#print axioms CardanoKeri.Registry.remove.eq_2
#print axioms CardanoKeri.Registry.setLeaf.eq_1
#print axioms CardanoKeri.Registry.setLeaf.eq_2
#print axioms CardanoKeri.Registry.setLeaf_map_fst
#print axioms CardanoKeri.Registry.stepFn.eq_1
#print axioms CardanoKeri.Registry.stepFn.eq_2
#print axioms CardanoKeri.Registry.stepFn.eq_3
#print axioms CardanoKeri.Registry.stepFn.eq_4
#print axioms CardanoKeri.Registry.stepFn.eq_5
#print axioms CardanoKeri.Registry.stepFn.eq_6
#print axioms CardanoKeri.Registry.stepFn.eq_7
#print axioms CardanoKeri.Registry.stepFn_contribute_iff
#print axioms CardanoKeri.Registry.stepFn_convictCkpt_iff
#print axioms CardanoKeri.Registry.stepFn_fold_iff
#print axioms CardanoKeri.Registry.stepFn_pause_iff
#print axioms CardanoKeri.Registry.stepFn_reap_iff
#print axioms CardanoKeri.Registry.stepFn_resume_iff
#print axioms CardanoKeri.Registry.stepFn_retract_iff
#print axioms CardanoKeri.Samaritan.FoldFlow.mk.inj
#print axioms CardanoKeri.Samaritan.FoldFlow.mk.injEq
#print axioms CardanoKeri.Samaritan.FoldFlow.mk.sizeOf_spec
#print axioms CardanoKeri.Samaritan.Reap.hFund
#print axioms CardanoKeri.Samaritan.Reap.mk.inj
#print axioms CardanoKeri.Samaritan.Reap.mk.injEq
#print axioms CardanoKeri.Samaritan.Reap.mk.sizeOf_spec
#print axioms CardanoKeri.Samaritan.ReapFlow.mk.inj
#print axioms CardanoKeri.Samaritan.ReapFlow.mk.injEq
#print axioms CardanoKeri.Samaritan.ReapFlow.mk.sizeOf_spec
#print axioms CardanoKeri.Samaritan.fold.eq_1
#print axioms CardanoKeri.Samaritan.fold_conserves
#print axioms CardanoKeri.Samaritan.reap.eq_1
#print axioms CardanoKeri.Samaritan.reap_conserves
#print axioms CardanoKeri.Samaritan.reap_conserves._proof_1_2
#print axioms CardanoKeri.Samaritan.reaper_recovers
#print axioms CardanoKeri.Samaritan.reaper_recovers._proof_1_3
#print axioms CardanoKeri.Samaritan.samaritan_never_loses
#print axioms CardanoKeri.Samaritan.samaritan_never_loses._proof_1_3
#print axioms CardanoKeri.Samaritan.self_folding_reaper_never_loses
#print axioms CardanoKeri.Samaritan.self_folding_reaper_never_loses._proof_1_3
#print axioms CardanoKeri.Samaritan.unprofitable_when_tip_too_high
#print axioms CardanoKeri.Samaritan.unprofitable_when_tip_too_high._proof_1_3
