import Blaster
import CardanoLedgerApi.V3
import PlutusCore.UPLC
import KeriBlaster.S2Cek
import KeriBlaster.S2Evidence
import KeriBlaster.S2Fixtures

/-!
Elaborating these imports proves that the exact Lean-Blaster,
PlutusCoreBlaster, and CardanoLedgerApiBlaster packages form one compatible
pinned build graph.

`KeriBlaster.S2Evidence` carries the production `#import_uplc` surface, so the
flake-owned `blaster` build, runner, and check all elaborate the exact
generated artifacts. Preparation and SMT properties begin in later slices. A
future successful solver result is reported as `SMT-VALID (no proof term)`,
never as a kernel proof.

This module is also the evidence entry point. It re-reads every generated
artifact at run time, proves each one decodes to the value that was imported
at elaboration time, and emits only rows it has actually computed. The
falsification controls run through this same entry point, so a control
perturbs the real checking path rather than a copy of it.
-/

open KeriBlaster.S2
open PlutusCore.UPLC.PlutusScript (PlutusScript)
open PlutusCore.UPLC.Term (BuiltinFun Program)
open PlutusCore.UPLC.ScriptEncoding.Internal (singleCborEncodedScriptFromHex?)

namespace KeriBlaster.Evidence

/-- Which falsification control is active, if any.

Each control perturbs one controlled input and requires the ordinary checking
path to reject it. `none` is the honest production run.
-/
inductive Control
  /-- an exact production import is missing from the emitted set -/
  | removedImport (title : String)
  /-- a generated artifact is replaced by a different production program -/
  | substitutedArtifact (title : String)
  /-- a computed row is replaced by a literal while its input is perturbed -/
  | literalizedEvidence
  /-- an extra context, byte-identical to one already applied, is added to the
  list a purpose block runs; the emitted distinct count must drop below the
  applied count -/
  | duplicatedContext
  /-- no perturbation: the real production run -/
  | none
  deriving Repr

/-- Read the active control from the environment. -/
def readControl : IO Control := do
  let kind ← IO.getEnv "S2_CONTROL"
  let title := (← IO.getEnv "S2_CONTROL_TITLE").getD ""
  match kind with
  | some "removed-import" => return .removedImport title
  | some "substituted-artifact" => return .substitutedArtifact title
  | some "literalized-evidence" => return .literalizedEvidence
  | some "duplicated-context" => return .duplicatedContext
  | some other => throw (IO.userError s!"unknown S2_CONTROL: {other}")
  | Option.none => return .none

/-- One manifest row: title, declared parameter count, artifact hash.

The manifest is generated by the flake from the SHA-bound blueprint. Its
parameter counts and hashes are the arity and identity evidence; this module
never writes them down.
-/
structure ManifestRow where
  title : String
  params : String
  hash : String
  deriving Repr

/-- Parse the generated manifest. -/
def parseManifest (contents : String) : Except String (List ManifestRow) :=
  let lines := contents.trim.splitOn "\n" |>.filter (fun l => !l.trim.isEmpty)
  lines.foldlM
    (fun rows line =>
      match line.splitOn "\t" with
      | [title, params, hash] =>
          pure (rows ++ [{ title := title, params := params, hash := hash }])
      | _ => throw s!"malformed manifest row: {line}")
    []

/-- A faithful structural rendering, used to compare a program decoded at run
time with the value imported at elaboration time. -/
def renderProgram (program : Program) : String := toString (repr program)

/-- Emit the computed decoded-builtin facts for one program.

These are syntactic occurrence facts. They are never reported as
reachability, which is an observation of the pinned CEK.
-/
def decodedRow (entry : ProductionProgram) : String :=
  let builtins := decodedBuiltins entry
  let xorOccurrences := builtinOccurrences .XorByteString entry
  s!"S2.decoded title={entry.title} distinct_builtins={builtins.length}" ++
    s!" xor_bytearray_occurrences={xorOccurrences}"

/-- One observer, named by the two titles whose programs must be identical. -/
structure ObserverPair where
  /-- short observer name used in the emitted rows -/
  name : String
  /-- the withdraw title, which the reward purpose exercises -/
  withdrawTitle : String
  /-- the publish title, which the certify purpose exercises -/
  publishTitle : String
  /-- the declared parameters, applied before the single context.

  These carry their declared *types*, not a uniform placeholder: passing an
  integer where the validator declares a `PolicyId` made every
  `observer_lifecycle` run fail identically at `UnBData` before it could
  discriminate purpose at all.
  -/
  parameters : List PlutusCore.Data.Data
  /-- the rewarding context this observer's withdraw branch is exercised with.

  The three withdraw branches validate different things and demand different
  redeemer and transaction shapes, so a single shared reward context can only
  reach the logic of at most one of them. Carrying it per observer is what
  lets one family's fixture deepen without disturbing the others' evidence.
  -/
  rewardContext : PlutusCore.Data.Data

/-- The three observer pairs. -/
def observerPairs : List ObserverPair :=
  [ { name := "observer_lifecycle"
    , withdrawTitle := "checkpoint_observer.observer_lifecycle.withdraw"
    , publishTitle := "checkpoint_observer.observer_lifecycle.publish"
      -- _version : Int, hash_proof_policy : PolicyId (bytes), d_reg : Int
    , parameters :=
        [ .I 0
        , .B (KeriBlaster.S2.Fixtures.label "s2-hash-proof-policy")
        , .I 0 ]
      -- Still the generic rewarding context: `validate_registration` wants
      -- `own_ref == None`, a `RegistrationEvidence` payload, a hash-proof
      -- input and a matching burn. Its withdraw-path fixture is not built
      -- yet, and this run must not pretend otherwise.
    , rewardContext := KeriBlaster.S2.Fixtures.rewardData }
  , { name := "observer_advance"
    , withdrawTitle := "checkpoint_observer.observer_advance.withdraw"
    , publishTitle := "checkpoint_observer.observer_advance.publish"
      -- _version : Int
    , parameters := [ .I 0 ]
      -- The one fixture built to reach a withdraw branch's actual logic.
    , rewardContext := KeriBlaster.S2.Fixtures.advanceRewardData }
  , { name := "observer_enforcement"
    , withdrawTitle := "checkpoint_observer.observer_enforcement.withdraw"
    , publishTitle := "checkpoint_observer.observer_enforcement.publish"
      -- _version : Int
    , parameters := [ .I 0 ]
      -- `validate_enforcement` dispatches on the Freeze/Convict tags and
      -- resolves a role-derived address; its own fixture is not built yet.
    , rewardContext := KeriBlaster.S2.Fixtures.rewardData }
  ]

/-- A `Data` argument as a UPLC term. -/
def dataTerm (value : PlutusCore.Data.Data) : PlutusCore.UPLC.Term.Term :=
  .Const (.Data value)

/-- Deduplicate `Data` values structurally, so a count of distinct contexts
is computed rather than written down. -/
def distinctData (values : List PlutusCore.Data.Data) :
    List PlutusCore.Data.Data :=
  values.foldl
    (fun seen value =>
      if seen.any (fun kept => toString (repr kept) == toString (repr value))
      then seen else seen ++ [value])
    []

/-- The step budget the purpose runs are given. Reported with the result so a
settled outcome is distinguishable from a bounded one. -/
def purposeBudget : Nat := 200000

/-- The bare constructor name of a builtin, without its namespace path.

`repr` renders `PlutusCore.UPLC.Term.BuiltinFun.Blake2b_256`, but the record
row names the builtin itself. Taking the final dot-component derives that
name from the observed value instead of writing the same name down a second
time where it could drift from what actually failed.
-/
def shortBuiltinName (builtin : BuiltinFun) : String :=
  let rendered := toString (repr builtin)
  match (rendered.splitOn ".").getLast? with
  | some name => name
  | none => rendered

/-- The limiting class a settled outcome licenses, if any.

Only a builtin dispatch that the pinned evaluator refused licenses
`builtin-support`. A validator rejecting its own input is a different fact and
licenses nothing, so this returns `none` and the record row is not emitted.
-/
def limitingClassOf (trace : KeriBlaster.S2.Cek.Trace) : Option String :=
  if KeriBlaster.S2.Cek.errorKind trace == "builtin-dispatch" then
    some "builtin-support"
  else
    none

/-- What one observer's reward run actually did, kept so the record rows are
derived from observations rather than from the author's memory of them. -/
structure RewardObservation where
  /-- short observer name, as emitted -/
  name : String
  /-- exact blueprint title of the withdraw program that was run -/
  title : String
  /-- the trace the pinned machine produced -/
  trace : KeriBlaster.S2.Cek.Trace

/-- The preparation runs this build performs.

Empty, and that emptiness is the whole basis of the
`hash_proof_preparation basis=not-executed` record. Declaring it as a list
rather than asserting the fact in prose means that adding a preparation run
without revisiting the record makes the guard below reject it.
-/
def preparationCases : List (String × PlutusCore.Data.Data) := []

end KeriBlaster.Evidence

open KeriBlaster.Evidence

/-- Evidence entry point.

Fails, loudly and non-zero, whenever a generated artifact is absent, fails to
decode, or decodes to something other than the imported value; whenever the
manifest disagrees with the registry; and whenever an active falsification
control's perturbation is not rejected.
-/
def main : IO UInt32 := do
  let control ← readControl
  let some artifactDir ← IO.getEnv "S2_ARTIFACTS"
    | do
      IO.eprintln "S2: S2_ARTIFACTS is not set"
      return 1
  let manifestPath := System.FilePath.mk artifactDir / "s2-manifest.tsv"
  let manifestContents ← IO.FS.readFile manifestPath
  let rows ←
    match parseManifest manifestContents with
    | .ok rows => pure rows
    | .error err => do
      IO.eprintln s!"S2: {err}"
      return 1

  -- The manifest and the imported registry must agree exactly, in order.
  if rows.length != registry.length then
    IO.eprintln s!"S2: manifest has {rows.length} rows, registry has {registry.length}"
    return 1

  -- Under the removed-import control one exact production entry is dropped
  -- from the emitted set. The cardinality check above is what must reject it.
  let emitted :=
    match control with
    | .removedImport title =>
        registry.filter (fun (entry : ProductionProgram) => entry.title != title)
    | _ => registry

  if emitted.length != rows.length then
    IO.eprintln s!"S2: emitted {emitted.length} programs but the manifest declares {rows.length}"
    match control with
    | .removedImport title => IO.eprintln s!"S2: removed-import control dropped {title}"
    | _ => pure ()
    return 1

  for (row, entry) in rows.zip registry do
    if row.title != entry.title then
      IO.eprintln s!"S2: manifest title {row.title} does not match registry title {entry.title}"
      return 1

    -- Under the substituted-artifact control this title reads a different
    -- production program's bytes. Re-decoding must not match the import.
    let readTitle :=
      match control with
      | .substitutedArtifact title =>
          if title == row.title then
            (registry.find?
              (fun (entry : ProductionProgram) => entry.title != row.title)).elim
              row.title (fun other => other.title)
          else row.title
      | _ => row.title
    let hexPath := System.FilePath.mk artifactDir / s!"{readTitle}.hex"
    let hex ← IO.FS.readFile hexPath
    match singleCborEncodedScriptFromHex? hex.trim with
    | .error err => do
        IO.eprintln s!"S2: {row.title} generated artifact failed to decode: {err}"
        return 1
    | .ok decoded =>
        if renderProgram decoded != renderProgram entry.program.script then
          IO.eprintln s!"S2: {row.title} generated artifact does not equal the imported program"
          return 1
        IO.println s!"S2.import title={row.title} params={row.params} program_sha256={row.hash}"

  -- Computed decoded inventory. Under the literalized-evidence control the
  -- emitted inventory is replaced by a literal while the real input is
  -- perturbed; `matchesDecodedInventory` is what must reject it.
  let claimedInventory : List (String × List BuiltinFun) :=
    match control with
    | .literalizedEvidence => [("checkpoint.checkpoint.spend", [])]
    | _ => decodedInventory
  if !matchesDecodedInventory claimedInventory then
    IO.eprintln "S2: emitted inventory is not the computed decoded inventory (literalized)"
    return 1

  for entry in emitted do
    IO.println (decodedRow entry)

  IO.println s!"S2.decoded-audit programs={auditProgramCount} distinct_builtins={decodedBuiltinsAcrossRegistry.length}"

  -- The advance withdraw-path fixture carries hand-written byte strings
  -- whose widths are protocol surface. A miscount would silently change the
  -- preimage `deriveAidAssetName` hashes, so the widths are checked against
  -- what the protocol fixes rather than against the author's counting.
  for (fieldName, actual, expected) in KeriBlaster.S2.Fixtures.advanceFixtureWidths do
    if actual != expected then
      IO.eprintln s!"S2: advance fixture field {fieldName} is {actual} bytes, protocol fixes {expected}"
      return 1

  -- What the reward runs actually did, and every builtin the machine really
  -- evaluated anywhere. The terminal-FAIL and UNPROVED records below are
  -- derived from these, so no record can outlive the observation it claims.
  let mut rewardObservations : List RewardObservation := []
  let mut reachedAnywhere : List BuiltinFun := []

  -- Purpose behaviour. Each observer pair is byte-identical, so the block
  -- binds ONE program value and varies only the applied context. The
  -- identity is asserted rather than assumed: if a pair were ever not
  -- identical the block fails instead of emitting a row about it.
  for pair in observerPairs do
    let some withdrawEntry :=
        registry.find? (fun (e : ProductionProgram) => e.title == pair.withdrawTitle)
      | do
        IO.eprintln s!"S2: no registry entry for {pair.withdrawTitle}"
        return 1
    let some publishEntry :=
        registry.find? (fun (e : ProductionProgram) => e.title == pair.publishTitle)
      | do
        IO.eprintln s!"S2: no registry entry for {pair.publishTitle}"
        return 1
    if renderProgram withdrawEntry.program.script
        != renderProgram publishEntry.program.script then
      IO.eprintln s!"S2: {pair.name} withdraw and publish programs are not identical; a purpose proof over them would not be a purpose proof"
      return 1

    -- One program value, bound once. Nothing below can vary the bytes.
    let program := withdrawEntry.program.script
    let arguments := pair.parameters.map dataTerm

    -- The one list that drives the runs. Both emitted counts are derived
    -- from it, so a count cannot disagree with what was actually applied.
    let productionCases : List (String × PlutusCore.Data.Data) :=
      [ ("certify", KeriBlaster.S2.Fixtures.certifyData)
      , ("wrong_certify", KeriBlaster.S2.Fixtures.wrongCertifyData)
      , ("wrong_reward", KeriBlaster.S2.Fixtures.wrongRewardData)
      , ("reward", pair.rewardContext)
      ]

    -- Under the duplicated-context control one further context is applied
    -- that is byte-identical to a context already in the list. It is run
    -- through the machine like any other case, so `applied` still counts
    -- real runs; only `distinct` may differ. This is the perturbation that
    -- makes the distinct-context derivation observable: it has otherwise
    -- only ever produced the same number as the literal it replaced.
    let cases : List (String × PlutusCore.Data.Data) :=
      match control with
      | .duplicatedContext =>
          productionCases
            ++ [("certify_duplicate", KeriBlaster.S2.Fixtures.certifyData)]
      | _ => productionCases

    let mut performed := 0
    for (caseName, context) in cases do
      let trace :=
        KeriBlaster.S2.Cek.runProgram program (arguments ++ [dataTerm context])
          purposeBudget
      let attributed := match trace.lastBuiltin with
        | some found => s!"{repr found}"
        | none => "none"
      -- The builtin whose own dispatch the pinned evaluator refused, which
      -- is a different fact from the last builtin in hand and is the only
      -- one that can name an unsupported builtin.
      let dispatchFailed := match trace.dispatchFailure with
        | some found => s!"{repr found}"
        | none => "none"
      -- No bare failure may enter the evidence. An `Error` the machine
      -- cannot attribute to a named builtin says only that something went
      -- wrong somewhere, which is not an observation anyone can act on --
      -- and it is exactly the shape a reached-but-unsupported builtin would
      -- take if the attribution were dropped. So it is rejected here rather
      -- than emitted as a nameless row.
      if KeriBlaster.S2.Cek.errored trace
          && trace.lastBuiltin.isNone && trace.dispatchFailure.isNone then
        IO.eprintln s!"S2: {pair.name} case {caseName} errored after {trace.steps} steps with no builtin to attribute it to; this would be a bare failure in the evidence"
        return 1
      IO.println s!"S2.purpose-run observer={pair.name} case={caseName} outcome={KeriBlaster.S2.Cek.outcome trace} steps={trace.steps} reached_builtins={trace.reached.length} last_builtin={attributed} error_kind={KeriBlaster.S2.Cek.errorKind trace} dispatch_failed_builtin={dispatchFailed}"
      performed := performed + 1
      reachedAnywhere := trace.reached.foldl
        (fun seen found => if seen.contains found then seen else seen ++ [found])
        reachedAnywhere
      -- Only the production reward case feeds the record. The duplicated
      -- context is a control on the counting, not an observation about a
      -- withdraw path.
      if caseName == "reward" then
        rewardObservations := rewardObservations ++
          [{ name := pair.name, title := pair.withdrawTitle, trace := trace }]

    -- A wrong count is observable: the emitted figure is the length of the
    -- driving list, and the block fails if fewer runs were actually made.
    let applied := cases.length
    let distinct := (distinctData (cases.map (fun c => c.2))).length
    if performed != applied then
      IO.eprintln s!"S2: {pair.name} performed {performed} runs but is about to claim {applied}"
      return 1

    -- The two counts must move apart exactly when, and only when, the input
    -- is perturbed. A `distinct` that is really `applied` under another name
    -- passes the production branch and fails the control branch; a
    -- `distinct` frozen at a literal fails whichever branch it does not
    -- happen to match. Neither branch can be satisfied by a written-down
    -- number, and the difference is caused rather than awaited.
    match control with
    | .duplicatedContext =>
        if distinct >= applied then
          IO.eprintln s!"S2: {pair.name} duplicated-context control applied {applied} contexts of which one was a duplicate, yet computed {distinct} distinct; the distinct count is not derived from the applied contexts"
          return 1
    | _ =>
        if distinct != applied then
          IO.eprintln s!"S2: {pair.name} production fixtures are not pairwise distinct: applied {applied}, distinct {distinct}; the purpose block would be testing fewer contexts than it claims"
          return 1

    IO.println s!"S2.purpose-binding observer={pair.name} program_sha256={(rows.find? (fun r => r.title == pair.withdrawTitle)).elim "unknown" (fun r => r.hash)} applied_contexts={applied} distinct_contexts={distinct}"

  /- ## The terminal FAIL record (milestone ruling A-005)

  S2's production tractability result is a terminal FAIL with limiting class
  `builtin support`. These rows publish it.

  Every field that *can* be observed is taken from the run that just
  happened: the observer, the case, the failing builtin's own name, the
  program hash from the generated manifest, and the limiting class derived
  from the error classification. Nothing here is emitted unconditionally --
  if the machine ever stopped failing at an unsupported builtin dispatch,
  these guards refuse to publish a FAIL record about it, which is the
  property that keeps this from being a literal wearing a computation's
  clothes.

  Two identifiers cannot be computed here and are supplied by the flake:
  the pinned evaluator revision, which the flake derives from the actual
  locked input rather than transcribing, and the SHA-256 of the decisive run
  log, which is a *previous* run's artifact living outside the build sandbox.
  The v2 gate re-hashes that real file itself before accepting any row that
  names it, so the constant cannot drift unnoticed.
  -/
  let some pinnedRev ← IO.getEnv "S2_PINNED_PLUTUS_CORE_REV"
    | do
      IO.eprintln "S2: S2_PINNED_PLUTUS_CORE_REV is not set; the record cannot name the evaluator it indicts"
      return 1
  let some decisiveLogSha ← IO.getEnv "S2_DECISIVE_LOG_SHA256"
    | do
      IO.eprintln "S2: S2_DECISIVE_LOG_SHA256 is not set; the record cannot bind its decisive evidence"
      return 1

  let some advance := rewardObservations.find? (fun o => o.name == "observer_advance")
    | do
      IO.eprintln "S2: no observer_advance reward observation; the terminal FAIL record has no basis"
      return 1
  /- ### The observer_advance terminal FAIL record — scoped by #234

  The advance family moved in #219 (PR #222). Under the post-#219 program this
  reward is a term error rather than a refused builtin dispatch, so the record
  below no longer describes it.

  The guards are unchanged and still decide: if the machine is still failing at
  an unsupported builtin dispatch, the FAIL record is published exactly as
  before, so a regression to the old behaviour is still caught. When it is not,
  this run publishes an explicit NON-CLAIM rather than a stale record — and
  rather than a false one adjusted to keep the build green.

  Establishing the post-#219 (and post-Conway) advance behaviour is #246's
  work, not this run's. This run has not observed it and does not claim it.
  -/
  let decisiveBuiltin? ← match limitingClassOf advance.trace with
    | none => do
        IO.println s!"S2.not-established subject=observer_advance-reward observed={KeriBlaster.S2.Cek.errorKind advance.trace} required_basis=refused-builtin-dispatch owner=#246 reason=advance-family-moved-in-219"
        pure none
    | some limitingClass => do
        let some failingBuiltin := advance.trace.dispatchFailure
          | do
            IO.eprintln "S2: observer_advance reward names no refused builtin; the record would be unattributed"
            return 1
        let some advanceRow := rows.find? (fun r => r.title == advance.title)
          | do
            IO.eprintln s!"S2: no manifest row for {advance.title}; the record cannot bind a program identity"
            return 1
        IO.println s!"S2.result verdict=FAIL limiting_class={limitingClass} observer={advance.name} case=reward dispatch_failed_builtin={shortBuiltinName failingBuiltin} program_sha256={advanceRow.hash} pinned_rev={pinnedRev} decisive_log_sha256={decisiveLogSha}"
        pure (some failingBuiltin)

  /- ## What this run does NOT establish

  These are the non-claims made checkable. Each is emitted only while the
  run itself still supports it, so the day one of them becomes false the
  build fails instead of publishing a stale disclaimer.
  -/

  -- `xor_bytearray` occurs in the decoded programs and has never been
  -- reached. Both halves are required: without the occurrences the basis is
  -- wrong, and if it were ever reached the claim is simply false.
  if !decodedBuiltinsAcrossRegistry.contains .XorByteString then
    IO.eprintln "S2: xor_bytearray is not syntactically present, so basis=syntactic-occurrences-only is the wrong basis"
    return 1
  if reachedAnywhere.contains .XorByteString then
    IO.eprintln "S2: xor_bytearray WAS reached by the pinned machine; it may not be recorded as reached=NO and this run's classification must be revisited"
    return 1
  IO.println "S2.unproved subject=xor_bytearray basis=syntactic-occurrences-only reached=NO"

  -- Hash-proof preparation was not executed, and the empty case list above
  -- is what makes that true rather than merely asserted.
  if preparationCases.length != 0 then
    IO.eprintln s!"S2: {preparationCases.length} preparation cases exist, so basis=not-executed is no longer true"
    return 1
  IO.println "S2.unproved subject=hash_proof_preparation basis=not-executed reached=NO"

  -- The other two withdraw paths stopped at an earlier refused dispatch, so
  -- nothing is known about what they would reach beyond it. Requiring the
  -- earlier failure to be a *different* builtin is what makes
  -- `bounded-at-earlier-dispatch-failure` an observation.
  for (observerName, subject) in
      [ ("observer_lifecycle", "observer_lifecycle_withdraw")
      , ("observer_enforcement", "observer_enforcement_withdraw") ] do
    let some observation := rewardObservations.find? (fun o => o.name == observerName)
      | do
        IO.eprintln s!"S2: no reward observation for {observerName}; its bound cannot be recorded"
        return 1
    -- These bounds are stated RELATIVE to the decisive advance path. When that
    -- path is not established (post-#219), their basis does not exist either,
    -- so they are published as explicit non-claims rather than as bounds
    -- against a builtin this run never identified.
    match decisiveBuiltin? with
    | none =>
      IO.println s!"S2.not-established subject={subject} required_basis=bounded-at-earlier-dispatch-failure owner=#246 reason=decisive-advance-path-not-established"
    | some failingBuiltin => do
      let some earlier := observation.trace.dispatchFailure
        | do
          IO.eprintln s!"S2: {observerName} reward did not stop at a refused dispatch; basis=bounded-at-earlier-dispatch-failure is unsupported"
          return 1
      if earlier == failingBuiltin then
        IO.eprintln s!"S2: {observerName} reward stopped at {shortBuiltinName earlier}, the same builtin as the decisive path; it is not bounded earlier"
        return 1
      if observation.trace.reached.contains failingBuiltin then
        IO.eprintln s!"S2: {observerName} reward reached {shortBuiltinName failingBuiltin}; it may not be recorded as reached=NO"
        return 1
      IO.println s!"S2.unproved subject={subject} basis=bounded-at-earlier-dispatch-failure reached=NO"

  IO.println "S2.boundary crypto=UNINTERPRETED semantic_claims=LIMITED"
  return 0
