{- |
Module      : Main
Description : Haskell-to-Aiken theorem verdict vectors for T116-R4

Emits deterministic verdicts computed by the pure lifecycle mirror.  The
generated Aiken module is the parity boundary consumed by the 17 mechanically
named Aiken tests.
-}
module Main (main) where

import Cardano.KERI.AID.Checkpoint.LifecycleModel
import Data.Either (isLeft, isRight)
import System.Environment (getArgs)

main :: IO ()
main = do
    args <- getArgs
    case args of
        [] -> putStr output
        [path] -> writeFile path output
        _ -> error "usage: gen-lifecycle-trace-vectors [OUT_PATH]"

output :: String
output =
    unlines $
        [ "//// GENERATED by offchain/app/GenLifecycleTraceVectors.hs. DO NOT EDIT."
        , "//// `just check-lifecycle-trace-vectors` regenerates and rejects drift."
        , ""
        ]
            ++ [ "pub const " <> theorem <> ": Bool = " <> bool verdict
               | (theorem, verdict) <- theoremVerdicts
               ]

bool :: Bool -> String
bool True = "True"
bool False = "False"

theoremVerdicts :: [(String, Bool)]
theoremVerdicts =
    [ ("advance_totality", advanceTotality)
    , ("no_absorbing_busy_state", noAbsorbingBusyState)
    , ("adversarial_advance_is_progress", adversarialAdvanceIsProgress)
    , ("bounded_churn", boundedChurn)
    , ("armed_exclusive_window", armedExclusiveWindow)
    , ("bond_transfer_only_via_elapsed_window", bondTransferOnlyViaElapsedWindow)
    , ("abandonment_pays_exactly_B", abandonmentPaysExactlyB)
    , ("frozen_implies_true_silence", frozenImpliesTrueSilence)
    , ("close_lie_always_voidable", closeLieAlwaysVoidable)
    , ("close_at_tip_unchallengeable", closeAtTipUnchallengeable)
    , ("current_state_is_quiet", currentStateIsQuiet)
    , ("value_conservation", valueConservation)
    , ("value_conservation_trace", valueConservationTrace)
    , ("convict_dominance", convictDominance)
    , ("tombstone_terminal_but_no_aid_bar", tombstoneTerminalButNoAidBar)
    , ("replay_convergence", replayConvergence)
    , ("close_cycle_requires_elapsed_window", closeCycleRequiresElapsedWindow)
    ]

advanceTotality :: Bool
advanceTotality =
    fmap state (dispatch params aheadEnv active0 (Tx 0 Advance)) == Right (Active 1)

noAbsorbingBusyState :: Bool
noAbsorbingBusyState =
    isRight (dispatch params tipEnv active1 (Tx 0 (CloseIntent refund)))

adversarialAdvanceIsProgress :: Bool
adversarialAdvanceIsProgress =
    advanceTotality && hasEvent aheadEnv 1

boundedChurn :: Bool
boundedChurn =
    isRight $
        runTrace
            params
            (Env [0, 1, 2] False [])
            0
            initConfig
            [ Tx 0 Register
            , Tx 1 Advance
            , Tx 2 (Arm hunter)
            , Tx 12 Claim
            , Tx 12 Advance
            ]

armedExclusiveWindow :: Bool
armedExclusiveWindow =
    isRight (dispatch params aheadEnv armed0 (Tx 9 Advance))
        && all
            (isLeft . dispatch params aheadEnv armed0 . Tx 9)
            [Register, Arm hunter, Claim, CloseIntent refund, ChallengeClose hunter, FinalizeClose]

bondTransferOnlyViaElapsedWindow :: Bool
bondTransferOnlyViaElapsedWindow = case claimResult of
    Right cfg -> Transfer hunter (bond params) Bounty `elem` outflows (ledger cfg)
    Left _ -> False

abandonmentPaysExactlyB :: Bool
abandonmentPaysExactlyB = case dispatch params aheadEnv armed0 (Tx 10 Claim) of
    Right cfg ->
        state cfg == Frozen 0
            && outflows (ledger cfg) == [Transfer hunter (bond params) Bounty]
    Left _ -> False

frozenImpliesTrueSilence :: Bool
frozenImpliesTrueSilence =
    slot (Tx 0 (Arm hunter)) + freezeWindow params <= slot (Tx 10 Claim)
        && fmap state claimResult == Right (Frozen 0)

closeLieAlwaysVoidable :: Bool
closeLieAlwaysVoidable =
    isRight (dispatch params aheadEnv closing0 (Tx 0 (ChallengeClose hunter)))
        && isRight (dispatch params aheadEnv closing0 (Tx 0 Advance))

closeAtTipUnchallengeable :: Bool
closeAtTipUnchallengeable =
    isLeft (dispatch params tipEnv closing1 (Tx 20 (ChallengeClose hunter)))
        && isLeft (dispatch params tipEnv closing1 (Tx 20 Advance))
        && isRight (dispatch params tipEnv closing1 (Tx 20 FinalizeClose))

currentStateIsQuiet :: Bool
currentStateIsQuiet =
    isRight (dispatch params tipEnv active1 (Tx 0 (CloseIntent refund)))
        && all
            (isLeft . dispatch params tipEnv active1 . Tx 0)
            [Register, Advance, Arm hunter, Claim, ChallengeClose hunter, FinalizeClose, Convict hunter]

valueConservation :: Bool
valueConservation = case dispatch params aheadEnv initConfig (Tx 0 Register) of
    Right cfg -> balanced params initConfig && balanced params cfg
    Left _ -> False

valueConservationTrace :: Bool
valueConservationTrace = case runTraceStates
    params
    aheadEnv
    0
    initConfig
    [Tx 0 Register, Tx 0 (Arm hunter), Tx 10 Claim, Tx 10 Advance] of
    Right (configs, _) -> all (balanced params) configs
    Left _ -> False

convictDominance :: Bool
convictDominance =
    all
        (\cfg -> isRight (dispatch params forkEnv cfg (Tx 0 (Convict hunter))))
        [active0, armed0, frozen0, closing0]

tombstoneTerminalButNoAidBar :: Bool
tombstoneTerminalButNoAidBar =
    all
        (isLeft . dispatch params forkEnv tombstone0 . Tx 0)
        [Register, Advance, Arm hunter, Claim, CloseIntent refund, ChallengeClose hunter, FinalizeClose, Convict hunter]
        && case sysDispatch params aheadEnv system 2 (Tx 0 Register) of
            Right sys' ->
                lookupInstance 1 sys' == Just tombstone0
                    && fmap state (lookupInstance 2 sys') == Just (Active 0)
            Left _ -> False

replayConvergence :: Bool
replayConvergence =
    fmap
        state
        ( runTrace
            params
            (Env [0, 1, 2] False [])
            0
            initConfig
            [Tx 0 Register, Tx 1 Advance, Tx 2 Advance]
        )
        == Right (Active 2)

closeCycleRequiresElapsedWindow :: Bool
closeCycleRequiresElapsedWindow =
    isRight
        ( runTrace
            params
            tipEnv
            0
            initConfig
            [Tx 0 Register, Tx 1 (CloseIntent refund), Tx 21 FinalizeClose]
        )
        && 1 + closeWindow params <= 21

params :: Params
params = Params 2 5 3 10 20

aheadEnv :: Env
aheadEnv = Env [0, 1] False [0, 1]

tipEnv :: Env
tipEnv = Env [0, 1] False [0, 1]

forkEnv :: Env
forkEnv = Env [0, 1] True [0, 1]

hunter :: Addr
hunter = 7

refund :: Addr
refund = 8

active0 :: Config
active0 = balancedConfig (Active 0)

active1 :: Config
active1 = balancedConfig (Active 1)

armed0 :: Config
armed0 = balancedConfig (Armed 0 hunter 10)

frozen0 :: Config
frozen0 = balancedConfig (Frozen 0)

closing0 :: Config
closing0 = balancedConfig (Closing 0 refund 20)

closing1 :: Config
closing1 = balancedConfig (Closing 1 refund 20)

tombstone0 :: Config
tombstone0 = balancedConfig (Tombstone 0)

system :: Sys
system = Sys [(1, tombstone0), (2, initConfig)]

claimResult :: Either Rejection Config
claimResult =
    runTrace
        params
        aheadEnv
        0
        initConfig
        [Tx 0 Register, Tx 0 (Arm hunter), Tx 10 Claim]

balancedConfig :: MachState -> Config
balancedConfig machineState =
    Config machineState (Ledger (carried params machineState) [])
