name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onchain:
    name: Onchain (Aiken)
    runs-on: nixos
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: nix shell 'nixpkgs#aiken' --command aiken build
        working-directory: onchain

  offchain:
    name: Offchain (Haskell)
    runs-on: nixos
    steps:
      - uses: actions/checkout@v6
      - name: Unit tests
        run: nix build --no-link .#checks.x86_64-linux.unit-tests
        working-directory: offchain
